import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientBody from "./ClientBody";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DcoreAI Chat",
  description: "Generated by Dcore",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} scroll-smooth`}
      style={{ minHeight: "100vh" }}
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <Script
          crossOrigin="anonymous"
          src="//unpkg.com/same-runtime/dist/index.global.js"
        />
      </head>
      <body
        suppressHydrationWarning
        className="antialiased min-h-screen w-full flex flex-col bg-slate-50 dark:bg-slate-950 overflow-x-hidden font-sans"
        style={{
          minHeight: "100vh",
          WebkitOverflowScrolling: "touch",
          overflowX: "hidden",
        }}
      >
        <ClientBody>{children}</ClientBody>
      </body>
    </html>
  );
}
